project_name: kp

before:
  hooks:
    - go mod tidy

builds:
  - binary: kp
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

brews:
  - repository:
      owner: simonski
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/simonski/kp"
    description: "A terminal tool to manage encrypted key/value pairs"
    license: "MIT"
    test: |
      system "#{bin}/kp", "version"

changelog:
  sort: asc
